import type { Metadata } from "next";
import '@fontsource/open-sans';
import '@fontsource/roboto-mono';
import "./globals.css";
import { Open_Sans, Roboto_Mono } from "next/font/google";
import {
  ClerkProvider
} from "@clerk/nextjs";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<ClerkProvider>
  <html lang="en">
    <body
      className={`${openSans.variable} ${robotoMono.variable} antialiased`}
    >
      {children}
    </body>
  </html>
</ClerkProvider>
  );
}
